theme: jekyll-theme-minimal
is_project_page: false
github:
  is_project_page: false

title: Paulo Silveira
description: Site pessoal do Paulo Silveira. CEO da Alura, podcaster, handbalancer e ex-estudante de línguas e literatura
logo: https://www.dropbox.com/s/5pyebat8375dnzc/paulo_oculos_escuro.jpg?dl=0
